### ISSUE TITLE
Update `npm` version

### ISSUE THREAD

**Issue by jpmontez** [jpmontez/deploy#1]
```
    default: npm
    default:
    default: WARN
    default:
    default: notice
    default:  [SECURITY] constantinople has the following vulnerability: 1 critical. Go here for more details: https://nodesecurity.io/advisories?search=constantinople&version=3.0.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
    default: npm WARN
    default:  notice [SECURITY] uglify-js has the following vulnerability: 2 low. Go here for more details: https://nodesecurity.io/advisories?search=uglify-js&version=2.2.5 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
```

I don't know much about `npm` or its requirements, but this popped up when launching the `Vagrantfile`.

This should be a simple fix on the upstream image build, but one could argue that package dependencies should be handled by the automation rather than statically installed where its essentially immutable.
